# Generated by Django 5.1.7 on 2025-03-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("player_email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_name", models.CharField(max_length=100)),
                ("race_date", models.DateField()),
                ("race_finished", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RaceSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_season_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Predictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_prediction1", models.TextField()),
                ("player_prediction2", models.TextField()),
                ("player_prediction3", models.TextField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.players",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.race",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceFinishers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place1", models.TextField()),
                ("place2", models.TextField()),
                ("place3", models.TextField()),
                ("place4", models.TextField()),
                ("place5", models.TextField()),
                ("place6", models.TextField()),
                ("place7", models.TextField()),
                ("place8", models.TextField()),
                ("place9", models.TextField()),
                ("place10", models.TextField()),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.race",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.players",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.race",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="race",
            name="race_season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APT_Django.raceseason"
            ),
        ),
        migrations.CreateModel(
            name="SeasonScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.players",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.raceseason",
                    ),
                ),
            ],
        ),
    ]
