# Generated by Django 5.1.7 on 2025-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "APT_Django",
            "0002_rename_players_player_rename_predictions_prediction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="raceseason",
            name="ongoing",
            field=models.BooleanField(default=True),
        ),
    ]
