# Generated by Django 5.1.7 on 2025-05-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APT_Django", "0006_race_race_predictions_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceCups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cup_name", models.CharField(max_length=100)),
                ("ongoing", models.BooleanField(default=True)),
                (
                    "cup_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.raceseason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CupScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.player",
                    ),
                ),
                (
                    "cup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APT_Django.racecups",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="race",
            name="race_cup",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="APT_Django.racecups",
            ),
        ),
    ]
