# Generated by Django 5.1.7 on 2025-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APT_Django", "0008_rename_racecups_racecup"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="cup_stage",
            field=models.IntegerField(default=0),
        ),
    ]
